---
title: "Introduction to forest plots"
author: "Max Gordon"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Introduction to forest plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

[Forest plots](http://en.wikipedia.org/wiki/Forest_plot) date back to [1970s](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1120528/) and have most frequently been used for [meta-analysis](http://en.wikipedia.org/wiki/Meta-analysis), but are in no way restricted to these.  the `forestplot2` function of this package is a development of the [rmeta](http://cran.r-project.org/web/packages/rmeta/index.html)-package's `forestplot` function, hence the name. With the forestplot2 you can:

* **Text:**
    + Use a table of text, i.e. the text can consist of several columns if needed&dagger;
    + Use expressions within your text, e.g. `expression(beta)`
    + Set fontfamily for both summary and regular rows
* **Confidence intervals:**
    + Clip confidence intervals to arrows when they exceed specified limits&dagger;
    + Use multiple confidence bands for the same row
    + Choose between boxes, diamonds, points etc as estimate indicator
    + Make your own custom confidence interval drawing functions
* **Legends:**
    + Have legend on top or to the left
    + Have the legend within plot
    + Put a box around legend (sharp or rounded corners)
* **Other:**
    + Automatically adapts graph to viewport (graph) size
    + Have the zero-effect line as a line or a wide box
    + All arguments can be within one array

&dagger; Features present int the original `forestplot` functions.

Basic example
=============

Below is a basic example from the original `forestplot` function:

```{r}
# Cochrane data from the rmeta-package
cochrane_from_rmeta <- 
  structure(list(
    mean  = c(NA, NA, 0.578, 0.165, 0.246, 0.700, 0.348, 0.139, 1.017, NA, 0.531), 
    lower = c(NA, NA, 0.372, 0.018, 0.072, 0.333, 0.083, 0.016, 0.365, NA, 0.386),
    upper = c(NA, NA, 0.898, 1.517, 0.833, 1.474, 1.455, 1.209, 2.831, NA, 0.731)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -11L), 
    class = "data.frame")

tabletext<-cbind(
  c("", "Study", "Auckland", "Block", 
    "Doran", "Gamsu", "Morrison", "Papageorgiou", 
    "Tauesch", NA, "Summary"),
  c("Deaths", "(steroid)", "36", "1", 
    "4", "14", "3", "1", 
    "8", NA, NA),
  c("Deaths", "(placebo)", "60", "5", 
    "11", "20", "7", "7", 
    "10", NA, NA),
  c("", "OR", "0.58", "0.16", 
    "0.25", "0.70", "0.35", "0.14", 
    "1.02", NA, "0.53"))

forestplot2(tabletext, cochrane_from_rmeta,new_page = TRUE,
            is.summary=c(TRUE,TRUE,rep(FALSE,8),TRUE),
            clip=c(0.1,2.5), xlog=TRUE,
            col=meta.colors(box="royalblue",line="darkblue", summary="royalblue"))
```

